server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: name
      password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: log/studentapp.log
  pattern:
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    '[org.springframework.web]': warn
    '[org.hibernate]': info
    '[com.tpro]': info

management:  #actuator
 endpoints:
   web:
     exposure:
       include: ['health','loggers','env','beans']